name: "💡 Feature Request"
description: Propose a new capability or improvement for WalletSign
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Tell us what you’d like and why it helps.
  - type: textarea
    id: request
    attributes:
      label: What do you want and why?
      description: Include the problem, desired behavior, and who benefits.
      placeholder: e.g., Pin frequently used chains so I can switch faster without mis-signing
    validations:
      required: true
